# Generated by Django 4.1.5 on 2023-02-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freshers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='')),
                ('lastname', models.CharField(max_length=50, verbose_name='')),
                ('dob', models.CharField(max_length=50, verbose_name='')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('pno', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('pincode', models.CharField(max_length=50, verbose_name='')),
                ('state', models.CharField(max_length=50, verbose_name='')),
                ('tyop', models.CharField(max_length=50, verbose_name='')),
                ('tp', models.CharField(max_length=50, verbose_name='')),
                ('twyop', models.CharField(max_length=50, verbose_name='')),
                ('twp', models.CharField(max_length=50, verbose_name='')),
                ('diyop', models.CharField(max_length=50, verbose_name='')),
                ('dip', models.CharField(max_length=50, verbose_name='')),
                ('dyop', models.CharField(max_length=50, verbose_name='')),
                ('dwp', models.CharField(max_length=50, verbose_name='')),
                ('myop', models.CharField(max_length=50, verbose_name='')),
                ('mp', models.CharField(max_length=50, verbose_name='')),
                ('courses', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
